### ISSUE TITLE
Bugs Occurring in Built Game That Don't Occur in the Editor

### ISSUE THREAD

**Issue by scottlittle18** [scottlittle18/2D-Side-Scroller#2]
In the built game there are some objects that aren't working correctly and the "Last Modified" date recorded on the files is 8/21/2018 instead of the day it was built like the rest of the files in the newly built game folder.

To Recreate:
- Simply attempt to build and play the game while ensuring that the build is located in a completely different location than the project folder.

**Comment by dantogno** [comment]
@scottlittle18 you need to log specific individual issues, each described in enough detail that I A. understand what happens, and what ought to be happening but isn't. and B. how to reproduce this behavior.
