### ISSUE TITLE
You need to explain what button attacks, jumps, double jumps, and uses the door in-game

### ISSUE THREAD

**Issue by dantogno** [scottlittle18/2D-Side-Scroller#4]
A controls screen is the lazy, bad way out. Instead, come up with a smart tutorial that doesn't feel like one. Recall the mega man sequelitis video for inspiration. Design your initial puzzles carefully so that the initial tasks are straightforward and distinct. Display the input the player needs to succeed when they need to know it (either for the first time, or every time). For example: check out the floating button prompts in diablo 3 console version: https://youtu.be/ji2OkelR-eM?t=78

**Comment by scottlittle18** [comment]
Signs have been added to the first level that show the controls
